---
kind: pipeline
name: default

clone:

steps:
  - name: deploy
    image: joomlaprojects/docker-images:packager
    environment:
      update_host:
        from_secret: update_host
      update_user:
        from_secret: update_user
      update_key:
        from_secret: update_key
      RINGCENTRAL_WEBHOOK:
        from_secret: notification_url
      CLOUDFLARE_TOKEN:
        from_secret: CLOUDFLARE_TOKEN
      CLOUDFLARE_ZONE_ID:
        from_secret: CLOUDFLARE_ZONE_ID
    commands:
      - mkdir -p ~/.ssh
      - eval $(ssh-agent -s)
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - echo "$update_key" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-add
      - rclone config create update sftp host $update_host user $update_user port 22
      - rclone copy ./translation-cli/ update:/home/update1/translation-cli/
      - rclone copy ./www/ update:/home/update1/public_html/
      - /bin/cloudflare_clear_cache update.joomla.org/core
      - /bin/notify

  - name: buildfailure
    image: joomlaprojects/docker-images:packager
    environment:
      RINGCENTRAL_WEBHOOK:
        from_secret: notification_url
    commands:
      - /bin/notify
    when:
      status:
        - failure

trigger:
  branch:
    - master
  event:
    - push
---
kind: signature
hmac: da22e793d280a553b7d3d37baaf150299b965a8e3aafdd6e4d8998872a2fe39c

...
